# Default values for mytodo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: <region>.icr.io/<namespace>/mytodo-<lastname>
  tag: "1.0"
  pullPolicy: Always

# secret:
#   database: database-credentials

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
  path: /
  hosts:
    - todo.<cluster-name>.eu-de.containers.appdomain.cloud
  tls:
    - secretName: <cluster-name>
      hosts:
        - todo.<cluster-name>.eu-de.containers.appdomain.cloud

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 384Mi
  requests:
    cpu: 250m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
