apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: private
  namespace: openshift-ingress-operator
spec:
  replicas: 2
  domain: iro-483cccd2f0d38128dd40d2b711142ba9-0001.eu-de.containers.appdomain.cloud
  endpointPublishingStrategy:
    loadBalancer:
      scope: Internal
    type: LoadBalancerService
